### ISSUE TITLE
Double click behavior with block selections

### ISSUE THREAD

**Issue by lord** [71/dance#314] opened 2023-10-17 10:32 UTC
When character/block selection is enabled with

```
        "normal": {
            "cursorStyle": "block",
            "selectionBehavior": "character",
```

I think double clicking to select a word will instead select a word plus a single subsequent character?

**Comment by 71** [comment] 2023-10-19 15:28
Hey, and thanks for the report! Yep that sounds about right, can't believe I didn't think about that before. With that said I'm not sure how to fix this. I'll have to look into whether VS Code sends events when this happens, but AFAIK it doesn't, in which case we'd need to guess when a selection is caused by a double click, which may not be great...

**Comment by lord** [comment] 2023-10-21 14:44
Yea that sounds tricky! Should also add that after using Dance for a few days I've come to like your idea that even normal mode selections should live between characters :) So definitely don't consider this any kind of urgent request

**Comment by 71** [comment] 2023-10-22 15:51
Ah, I also realized this is the default VS Code behavior, AFAIK Dance doesn't do anything when selecting by mouse. The problem is that Dance reinterprets how the block character _should_ work for modal editing (i.e. it includes the last character in the selection, unlike VS Code), so Dance commands that select a word exclude the last character, but commands that operate on selections include that last character.

Additionally I expect that users who prefer the block character are also users who use the mouse less, so this is probably why there hasn't been an issue created about this until now. I will file this issue as `wontfix` for now, though I'm open to reopening it if this matters to somebody, though I'd like help to figure out how that should work.

**Closed by 71** 2023-10-22 15:51 UTC
Labels: bug, wontfix
