### ISSUE TITLE
Gnome 3 swap of CapsLock- and Esc-Key not respected

### ISSUE THREAD

**Issue by vonneudeck** [71/dance#136] opened 2021-03-05 21:05 UTC
For ergonomics I swapped CapsLock- and Esc-key on Gnome 3 with Wayland on Fedora Silverblue using `dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:swapescape']"`
When I am now installing VSCode as a flatpack, it respects that, but the dance extension does not.

I am not familiar enough with the problem space to judge if this is one of the drawbacks of https://github.com/71/dance/issues/77 or a genuine bug, but I wanted to link to it so that you can see that I respect your time and labour and looked for similar/adjacent issues before creating a new one.

**Comment by 71** [comment] 2021-03-05 21:40
Hey there, and no worries! This should be a VS Code issue, since Dance simply uses keybindings.

Can you try adding this line to the user preferences and reporting back?

```json
"keyboard.dispatch": "keyCode"
```

Source 1: https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings  
Source 2: https://github.com/VSCodeVim/Vim/issues/2859#issuecomment-406446365

**Comment by willhaslett** [comment] 2021-03-18 16:31
This workaround is working for me on up-to-date Linux Mint. Many thanks.

**Comment by 71** [comment] 2021-03-26 19:23
For reference, this is a duplicate of #119. I'll close this issue and add a notice in the README about it.

**Closed by 71** 2021-03-26 19:23 UTC
Labels: bug, duplicate
