### ISSUE TITLE
`d` with no selection does not delete a character

### ISSUE THREAD

**Issue by J-Fields** [71/dance#44] opened 2020-01-03 04:00 UTC
Correct me if I'm wrong - I'm very new to kakoune-style bindings, but I thought `d` without explicitly selecting anything should delete the character under the cursor. Dance doesn't seem to do that.

**Comment by 71** [comment] 2020-01-07 21:55
This is actually something I'm wondering about. I prefer considering that the selection can be empty (unlike Vim and Kakoune which have 1-character selections by default), but this _does_ cause issues when doing something simple like deleting or replacing a character. Should I change the behavior in those cases to remove the character on the right of the cursor, even though it is not in the current (empty) selection?

**Comment by J-Fields** [comment] 2020-01-07 22:06
Treating an empty selection (from VSCode's point of view) as a 1-character selection is my preference, but I can see the other side of it as well. Would it add too much complexity to make that behavior a configurable option?

**Comment by yuchenshi** [comment] 2020-01-07 22:35
Alternatively, can we have a configurable option to keep all selections non-empty? I don't know too much about the complexity, but it does solve the problem of having to special-case deleting / replacing, plus it might be easier for users like me who are coming from Vim/Kak to apply the muscle memory. I can also help with the implementation if needed.

**Comment by yuchenshi** [comment] 2020-01-15 23:38
@71 Just to double check, would you accept a PR that adds an option to keep all selections non-empty? I may give it a spin.

**Comment by 71** [comment] 2020-01-16 21:32
@yuchenshi Since this looks like a feature that would be wanted, sure! Typically configuration changes are handled in `src/extension.ts`, specifically using `observePreference`.

**Comment by yuchenshi** [comment] 2020-01-24 19:08
My first try at #48. Please let me know if that works for you.

**Comment by timjs** [comment] 2020-02-17 13:07
I'd really love to have this! It saves a lot of typing when I just want to replace/change/delete one character.

Next question is: should we change the cursor to reflect there is always a selection? I.e. use a block or bar cursor in normal mode?

Also, won't there be a problem with empty lines? Sitting on an empty line and having one character selected implies the newline char is selected. What is the expected behaviour of hitting `x`? Selecting the next line is consistent with the idea of having already "selected the empty line". However, it is inconsistent with the idea that `xd` will always delete the current line. It is my [main annoyance with Kakoune](https://github.com/mawww/kakoune/issues/2590) itself.

**Comment by osor-io** [comment] 2020-02-19 15:56
Just sliding here to say that I'd also like there to be an option to have the cursor be treated as a selection of size one for that one character, just for the replacing and deleting single characters bit. I didn't think about the gains if keeping it size zero but should be good as a setting :)

Thank you for this extension by the way! :D Great work

**Comment by 71** [comment] 2020-02-19 20:16
Always having it at a non-empty state is the best when it comes to editing IMO, but allowing it to be empty makes it closer to the initial VS Code behavior, in case only some features of Dance are wanted.

In any case, work is ongoing in #48, and I'd like to have this merged for the next release. If anyone could try @yuchenshi's fork (and my branch in https://github.com/71/dance/tree/allow-empty-selections), it would greatly help!

**Comment by timjs** [comment] 2020-02-20 08:16
Tested @yuchenshi branch, awesome! Like your workaround to not select newline chars.

Only thing to do in my opinion is to change the cursor from `line` to `underline` when in normal mode. 😄 Helps distinguishing normal and insert mode, and you're still able to see the difference between a single char selection and a multi-char selection (when using a block cursor this would not be obvious).

**Comment by 71** [comment] 2020-02-20 18:36
@timjs I tried it at the beginning of Dance and personally didn't like it, but I can't see why this shouldn't be configurable, like #27. Since #27 hasn't received an update in a while I'll probably add this myself and add the option to customize the cursor as well.

**Comment by 71** [comment] 2020-02-20 20:09
@timjs c0cea08 adds this.

**Closed** 2020-02-20 23:16 UTC
Labels: enhancement, question
