### ISSUE TITLE
Some option keybindings broken on macOS

### ISSUE THREAD

**Issue by adrusi** [71/dance#49] opened 2020-02-06 15:32 UTC
Typing Option+e, Option+i, Option+u, Option+n, and maybe some other keys on macOS will wait for the next character and put some diacritic mark on it (acute, circumflex, umlaut and tilde respectively). When using kakoune keybindings that are bound to these keys in vscode, such as <a-i> the OS will insert the diacritic mark before Dance gets invoked, and this makes those keybindings unusable.

**Comment by 71** [comment] 2020-02-19 19:42
Duplicate of #18.

**Closed by 71** 2020-02-19 19:42 UTC
Labels: duplicate
