### ISSUE TITLE
Search does not work when using a Swedish keyboard layout

### ISSUE THREAD

**Issue by Buffes** [71/dance#274] opened 2022-09-16 13:29 UTC
In normal mode, inputting '/' (shift-7 on the physical keyboard) with a Swedish keyboard layout does not bring up the search box, as it does when using a US layout. In insert mode it works as expected and inserts the character '/'.

OS: Windows 10

**Comment by 71** [comment] 2022-09-16 14:09
Closing as duplicate of #174. This is due to how key bindings are defined in VS Code. I'd like to tackle this at some point (and I want this to be the next "big" feature for Dance), but I haven't yet had time to design a solution. If you have any ideas, I'm all ears!

**Closed by 71** 2022-09-16 14:09 UTC
