### ISSUE TITLE
Cursor is inert on `w`/`W`/`e`/`E`/`b`/`B` when single char selection is on a one char word

### ISSUE THREAD

**Issue by timjs** [71/dance#68] opened 2020-03-05 17:39 UTC
Happens after update to 0.2.1

To reproduce:
0. Type `Class.method`
1. Place single char selection on `.`
2. Hit `w`/`W`/`e`/`E`/`b`/`B`

Expected output:
* Cursor moves

Actual output:
* Selection stays the same

**Comment by 71** [comment] 2020-03-07 16:53
I keep fighting with this issue, encountering many corner cases and coming up with tons of hacks. If anyone finds a way to make this work cleanly, I'll gladly take it.

**Comment by timjs** [comment] 2020-04-13 13:40
Oké, I've an idea about this. I think the root of the problem is that in Disallow Empty  mode, the cursor is _at a different place_ than in Allow Empty mode:

* Allow Empty: `|word`, and after selecting one char: `[w]|ord`
* Disallow Empty: `|[w]ord`

This gives a lot of corner cases!

How about removing the new disallow empty mode completely, and adding the following rule (which can obviously be hidden behind an option):

__When performing an operation, and there is no selection, perform the operation on the character on the right of the cursor.__

I.e. when we have `|word` and we hit `d`, `w` gets deleted because the selection is empty and it is the char to the right of the cursor. The same holds for `c`, `y`, `r`, `R`, ```, `&`, `~` and maybe some others I did not think about yet. Would be nice add this behaviour to `a` as well.

Advantages:
* Orthogonal to good old Allow Empty mode. Above operations just did nothing in that case.
* No two separate modes to keep track of, so less corner cases, and less bugs.
* Should be implementable a single check on the emptiness of a selection for every operator.
* Includes @yuchenshi idea of [keeping the selection empty at end of line but delete removes line break](https://github.com/71/dance/pull/48/commits/dd9ed3bf044241d577ee930bdc70c4b977369f6c).

**Comment by 71** [comment] 2020-04-14 14:58
Ah, unfortunately I went with the complete opposite approach for the refactor. I tried wrapping all interactions with `Selection` and `Position` behind wrappers, so that operations related to line endings and non-directional selections would be handled by the wrapper, instead of by the user. I also tried re-adding the ability to select line endings a-la Kakoune.

I'm also adding integration tests, so hopefully we'll never have regressions again, provided that the various edge cases of the tricky commands are properly tested.

Now, I certainly have a preference for doing things "my" way (enforcing non-empty selections) because I like the way it works (when it does work) *but* I do understand that your approach has significant advantages. It might have similar drawbacks to what we currently have, though. For instance (even though it's easy to handle), extending left or right from a selection would extend to a single-character selection, rather than two-characters.

**Comment by yuchenshi** [comment] 2020-04-14 17:15
I personally prefer the approach of keeping selection non empty better because I really hate to learn a third set of muscle memory in addition to Vim and Kakoune, so I really appreciate your work, @71! Let me know if I can help testing this out or anything -- I use Dance and Kak for my day job and I can definitely contribute to integration tests. TBH, our previous discussions about corner cases would have been much easier if we had the integration test framework in place.

**Comment by 71** [comment] 2020-04-14 17:41
Thanks for the help! I probably won't put many tests for the first commit since it will have many other features, but if you want to start making tests, I documented the syntax [here](https://gist.github.com/71/2341282e3c7ca76e3587da30ff992b0c).

As an example, here is a simple test for `select.to`:

```
{0}a|{0}bcabc

//== 0 > 1
//= dance.select.to.included
//= type:c
{0}abc|{0}abc

//== 1 > 2
//= dance.select.to.excluded
//= type:c
ab{0}cab|{0}c

//== 0 > 3
//= dance.count.2
//= dance.select.to.excluded
//= type:c
{0}abcab|{0}c

//== 3 > 4
//= dance.select.to.excluded
//= type:c
{0}abcab|{0}c
```

**Comment by yuchenshi** [comment] 2020-04-14 18:41
@71 The syntax seems great and I can probably get started soon. I do suggest giving sections names like `initial -> after_deletion` which is easier to read than `0 > 1`. I confused sections numbers with selection numbers when I first read through the syntax. (Also, using sequential numbering for tests makes inserting tests a pain in the ass, since you need to renumber all following tests and keep them in sync. This is a hard lesson that I've learned from my day job.)

**Comment by 71** [comment] 2020-04-14 19:05
Okay, great! Yeah numbers certainly are not explicit, but if we name everything it becomes too explicit (`goleft`, `goleftagain`, ...). It's not in the example above, but any non-whitespace name is okay, so in some tests I wrote `0 > 1`, `1 > 0.previous`, etc. As for re-numbering, I think the issue would be the same with names. If you rename your test, you have to rename it everywhere else (the order of the numbers does not matter, so you can always come back and add `6 > 12` or create an intermediate step at the end and add some `6 > 6.inter` and then `6.inter > 7` at some point).

**Comment by timjs** [comment] 2020-04-15 14:20
As long as the bugs will be squashed, and operations work on single characters, as well as on multi-char selections, I'll be happy ;-)

Integration tests are a good idea! The regressions in the last couple of releases annoyed me. Currently staying on 0.2.0.

Keep up the good work!

**Comment by tshort** [comment] 2020-04-16 17:10
I gave the `dev` branch a quick spin, and it's very nice. You cleaned up several little things that bugged me. Nice job, @71 !!

**Comment by tshort** [comment] 2020-04-30 11:08
Wow, the unstable branch is hopping. Kudos to @71 and @yuchenshi! Looking forward to trying it soon.

**Comment by 71** [comment] 2020-04-30 11:32
Ah, I'm glad! There was a lot of work and experimentation going on there but we're almost done. We might push this to master today or tomorrow, and then add some tests and update the extension in the store.

**Comment by yuchenshi** [comment] 2020-05-08 06:25
This is taking longer than we anticipated but we're still hacking around in the `unstable` branch. Stay tuned.

**Comment by yuchenshi** [comment] 2020-06-22 00:34
This is now merged to `master`. We appreciate any help on testing.

**Closed by yuchenshi** 2020-06-22 00:34 UTC
Labels: bug, help wanted
